/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'account-settings-tab': RouteRecordInfo<'account-settings-tab', '/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'admin-users-id': RouteRecordInfo<'admin-users-id', '/admin/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'authentication-register-multi-steps': RouteRecordInfo<'authentication-register-multi-steps', '/authentication/register-multi-steps', Record<never, never>, Record<never, never>>,
    'authentication-register-v1': RouteRecordInfo<'authentication-register-v1', '/authentication/register-v1', Record<never, never>, Record<never, never>>,
    'authentication-reset-password-v1': RouteRecordInfo<'authentication-reset-password-v1', '/authentication/reset-password-v1', Record<never, never>, Record<never, never>>,
    'authentication-two-steps-v1': RouteRecordInfo<'authentication-two-steps-v1', '/authentication/two-steps-v1', Record<never, never>, Record<never, never>>,
    'authentication-verify-email-v1': RouteRecordInfo<'authentication-verify-email-v1', '/authentication/verify-email-v1', Record<never, never>, Record<never, never>>,
    'business-statements': RouteRecordInfo<'business-statements', '/business/statements', Record<never, never>, Record<never, never>>,
    'components-alert': RouteRecordInfo<'components-alert', '/components/alert', Record<never, never>, Record<never, never>>,
    'components-avatar': RouteRecordInfo<'components-avatar', '/components/avatar', Record<never, never>, Record<never, never>>,
    'components-badge': RouteRecordInfo<'components-badge', '/components/badge', Record<never, never>, Record<never, never>>,
    'components-button': RouteRecordInfo<'components-button', '/components/button', Record<never, never>, Record<never, never>>,
    'components-chip': RouteRecordInfo<'components-chip', '/components/chip', Record<never, never>, Record<never, never>>,
    'components-dialog': RouteRecordInfo<'components-dialog', '/components/dialog', Record<never, never>, Record<never, never>>,
    'components-expansion-panel': RouteRecordInfo<'components-expansion-panel', '/components/expansion-panel', Record<never, never>, Record<never, never>>,
    'components-list': RouteRecordInfo<'components-list', '/components/list', Record<never, never>, Record<never, never>>,
    'components-menu': RouteRecordInfo<'components-menu', '/components/menu', Record<never, never>, Record<never, never>>,
    'components-pagination': RouteRecordInfo<'components-pagination', '/components/pagination', Record<never, never>, Record<never, never>>,
    'components-progress-circular': RouteRecordInfo<'components-progress-circular', '/components/progress-circular', Record<never, never>, Record<never, never>>,
    'components-progress-linear': RouteRecordInfo<'components-progress-linear', '/components/progress-linear', Record<never, never>, Record<never, never>>,
    'components-snackbar': RouteRecordInfo<'components-snackbar', '/components/snackbar', Record<never, never>, Record<never, never>>,
    'components-tabs': RouteRecordInfo<'components-tabs', '/components/tabs', Record<never, never>, Record<never, never>>,
    'components-timeline': RouteRecordInfo<'components-timeline', '/components/timeline', Record<never, never>, Record<never, never>>,
    'components-tooltip': RouteRecordInfo<'components-tooltip', '/components/tooltip', Record<never, never>, Record<never, never>>,
    'configuration-agencies': RouteRecordInfo<'configuration-agencies', '/configuration/agencies', Record<never, never>, Record<never, never>>,
    'configuration-brands': RouteRecordInfo<'configuration-brands', '/configuration/brands', Record<never, never>, Record<never, never>>,
    'configuration-mandates': RouteRecordInfo<'configuration-mandates', '/configuration/mandates', Record<never, never>, Record<never, never>>,
    'configuration-products': RouteRecordInfo<'configuration-products', '/configuration/products', Record<never, never>, Record<never, never>>,
    'configuration-products-id': RouteRecordInfo<'configuration-products-id', '/configuration/products/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'configuration-products-create': RouteRecordInfo<'configuration-products-create', '/configuration/products/create', Record<never, never>, Record<never, never>>,
    'dashboards-analytics': RouteRecordInfo<'dashboards-analytics', '/dashboards/analytics', Record<never, never>, Record<never, never>>,
    'dashboards-crm': RouteRecordInfo<'dashboards-crm', '/dashboards/crm', Record<never, never>, Record<never, never>>,
    'dashboards-crm-bkp': RouteRecordInfo<'dashboards-crm-bkp', '/dashboards/crm/bkp', Record<never, never>, Record<never, never>>,
    'dashboards-ecommerce': RouteRecordInfo<'dashboards-ecommerce', '/dashboards/ecommerce', Record<never, never>, Record<never, never>>,
    'extensions-swiper': RouteRecordInfo<'extensions-swiper', '/extensions/swiper', Record<never, never>, Record<never, never>>,
    'extensions-tour': RouteRecordInfo<'extensions-tour', '/extensions/tour', Record<never, never>, Record<never, never>>,
    'extra-login-registry': RouteRecordInfo<'extra-login-registry', '/extra/login-registry', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'forgot-password-v1': RouteRecordInfo<'forgot-password-v1', '/forgot-password-v1', Record<never, never>, Record<never, never>>,
    'general-calendar': RouteRecordInfo<'general-calendar', '/general/calendar', Record<never, never>, Record<never, never>>,
    'general-documents': RouteRecordInfo<'general-documents', '/general/documents', Record<never, never>, Record<never, never>>,
    'general-links': RouteRecordInfo<'general-links', '/general/links', Record<never, never>, Record<never, never>>,
    'lead-alfacom-solar-lead': RouteRecordInfo<'lead-alfacom-solar-lead', '/lead/alfacom-solar-lead', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'login-v1': RouteRecordInfo<'login-v1', '/login-v1', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'reports-admin': RouteRecordInfo<'reports-admin', '/reports/admin', Record<never, never>, Record<never, never>>,
    'reports-appointments': RouteRecordInfo<'reports-appointments', '/reports/appointments', Record<never, never>, Record<never, never>>,
    'reports-production': RouteRecordInfo<'reports-production', '/reports/production', Record<never, never>, Record<never, never>>,
    'reports-saved': RouteRecordInfo<'reports-saved', '/reports/saved', Record<never, never>, Record<never, never>>,
    'reports-saved-id': RouteRecordInfo<'reports-saved-id', '/reports/saved/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    'solar-categorie': RouteRecordInfo<'solar-categorie', '/solar/categorie', Record<never, never>, Record<never, never>>,
    'solar-coefficienti-produzione': RouteRecordInfo<'solar-coefficienti-produzione', '/solar/coefficienti-produzione', Record<never, never>, Record<never, never>>,
    'solar-pagamenti': RouteRecordInfo<'solar-pagamenti', '/solar/pagamenti', Record<never, never>, Record<never, never>>,
    'solar-prodotti': RouteRecordInfo<'solar-prodotti', '/solar/prodotti', Record<never, never>, Record<never, never>>,
    'solar-tetti': RouteRecordInfo<'solar-tetti', '/solar/tetti', Record<never, never>, Record<never, never>>,
    'solar-voci-economiche': RouteRecordInfo<'solar-voci-economiche', '/solar/voci-economiche', Record<never, never>, Record<never, never>>,
    'workflow-aipaperworks': RouteRecordInfo<'workflow-aipaperworks', '/workflow/aipaperworks', Record<never, never>, Record<never, never>>,
    'workflow-aipaperworks-id': RouteRecordInfo<'workflow-aipaperworks-id', '/workflow/aipaperworks/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'workflow-communications': RouteRecordInfo<'workflow-communications', '/workflow/communications', Record<never, never>, Record<never, never>>,
    'workflow-communications-id': RouteRecordInfo<'workflow-communications-id', '/workflow/communications/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'workflow-communications-create': RouteRecordInfo<'workflow-communications-create', '/workflow/communications/create', Record<never, never>, Record<never, never>>,
    'workflow-customers': RouteRecordInfo<'workflow-customers', '/workflow/customers', Record<never, never>, Record<never, never>>,
    'workflow-customers-id': RouteRecordInfo<'workflow-customers-id', '/workflow/customers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'workflow-customers-create': RouteRecordInfo<'workflow-customers-create', '/workflow/customers/create', Record<never, never>, Record<never, never>>,
    'workflow-paperworks': RouteRecordInfo<'workflow-paperworks', '/workflow/paperworks', Record<never, never>, Record<never, never>>,
    'workflow-paperworks-id': RouteRecordInfo<'workflow-paperworks-id', '/workflow/paperworks/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'workflow-paperworks-create': RouteRecordInfo<'workflow-paperworks-create', '/workflow/paperworks/create', Record<never, never>, Record<never, never>>,
    'workflow-paperworks-create-wizard': RouteRecordInfo<'workflow-paperworks-create-wizard', '/workflow/paperworks/create-wizard', Record<never, never>, Record<never, never>>,
    'workflow-preventivi': RouteRecordInfo<'workflow-preventivi', '/workflow/preventivi', Record<never, never>, Record<never, never>>,
    'workflow-tickets': RouteRecordInfo<'workflow-tickets', '/workflow/tickets', Record<never, never>, Record<never, never>>,
    'workflow-tickets-id': RouteRecordInfo<'workflow-tickets-id', '/workflow/tickets/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
